config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  get '/about' => 'site#about'
  get '/privacy' => 'site#privacy'
  get '/terms' => 'site#terms'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @title = "Welcome mate!"
  end

  def about
  end

  def privacy
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "TDC Rules!" %></title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to_unless_current "Home", root_path do
              content_tag(:span, "Home", class: "this-page")
              end%></li>
            <li><%= link_to_unless_current "About", about_path do
              content_tag(:span, "About", class: "this-page")
            end%></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->
    <main class="container">
      <%= yield %>
    </main>

    <footer class="footer">
      <div class="container">
        <nav class="pull-right">
          <%= link_to_unless_current "Privacy policy", privacy_path do |label|
            content_tag(:span, label, class: "this-page")
            end %> &middot;
            <%= link_to_unless_current "Terms of use", terms_path do |label|
            content_tag(:span, label, class: "this-page")
            end %>
        </nav>
        <p class="copyright">&copy; 2015 Learning the Rails. Yup.</p>
      </div>
    </footer>
  </body>
</html>

app/views/site/about.html.erb
<article>

  <header class="page-header">
    <h1> About us </h1>
  </header>
  <p> Here you can learn all about us! </p>
</article>

app/views/site/index.html.erb
<article>
  <header class="page-header">
    <h1><%= @title %></h1>
  </header>
  <p>Welcome to our brave new site!</p>
</article>

app/views/site/privacy.html.erb
<article>

<header class= "page-header">
  <h1> Privacy </h1>
</header>
<p> So private </p>

</article>

app/views/site/terms.html.erb
<article>

<header class= "page-header">
  <h1> Terms </h1>
</header>
<p>I'm sure you will find these terms more than resonable</p>

</article>